INSERT OR IGNORE INTO categories (
    category_id,
    name,
    label,
    direction,
    default_vat_rate,
    default_vat_deductible_pct,
    parent_id
)
VALUES
    (1, 'ci_services', 'Services', 'cash_in', NULL, NULL, NULL),
    (2, 'ci_training', 'Training', 'cash_in', NULL, NULL, NULL),
    (3, 'ci_products', 'Product Sales', 'cash_in', NULL, NULL, NULL),
    (4, 'ci_commissions', 'Commissions / Affiliate', 'cash_in', NULL, NULL, NULL),
    (5, 'ci_consulting', 'Consulting', 'cash_in', NULL, NULL, NULL),
    (6, 'ci_financial', 'Financial', 'cash_in', NULL, NULL, NULL),
    (7, 'ci_other', 'Other Income', 'cash_in', NULL, NULL, NULL),
    (8, 'co_marketing', 'Marketing', 'cash_out', NULL, NULL, NULL),
    (9, 'co_operations', 'Operations', 'cash_out', NULL, NULL, NULL),
    (10, 'co_people', 'People Costs', 'cash_out', NULL, NULL, NULL),
    (11, 'co_taxes', 'Owner / Company Taxes', 'cash_out', NULL, NULL, NULL),
    (12, 'co_services', 'Services & Subscriptions', 'cash_out', NULL, NULL, NULL),
    (13, 'co_financial', 'Financial', 'cash_out', NULL, NULL, NULL),
    (14, 'co_inventory', 'Inventory', 'cash_out', NULL, NULL, NULL),
    (15, 'co_capex', 'CAPEX', 'cash_out', NULL, NULL, NULL),
    (16, 'co_training_int', 'Training - Internal', 'cash_out', NULL, NULL, NULL),
    (17, 'co_training_del', 'Training - Delivery', 'cash_out', NULL, NULL, NULL),
    (18, 'co_private', 'Owner / Private', 'cash_out', NULL, NULL, NULL),
    (19, 'co_other', 'Other Expense', 'cash_out', NULL, NULL, NULL),

    (101, 'ci_services_test', 'Test', 'cash_in', 23, NULL, 1),
    (102, 'ci_services_package', 'Package', 'cash_in', 23, NULL, 1),
    (103, 'ci_services_bioresonance', 'Bioresonance', 'cash_in', 23, NULL, 1),
    (104, 'ci_services_dietetic', 'Dietetic', 'cash_in', 23, NULL, 1),
    (105, 'ci_services_naturopathic', 'Naturopathic', 'cash_in', 23, NULL, 1),
    (106, 'ci_training_income', 'Training Income', 'cash_in', 23, NULL, 2),
    (107, 'ci_products_accessories', 'Accessories / Ampulles', 'cash_in', 23, NULL, 3),
    (108, 'ci_products_zapper', 'Zapper / Chipcard', 'cash_in', 23, NULL, 3),
    (109, 'ci_products_supplements', 'Supplements', 'cash_in', 23, NULL, 3),
    (110, 'ci_products_trikombin', 'Trikombin', 'cash_in', 23, NULL, 3),
    (111, 'ci_commissions_affiliate', 'Affiliate Income', 'cash_in', 23, NULL, 4),
    (112, 'ci_commissions_partner', 'Partner Commissions', 'cash_in', 23, NULL, 4),
    (113, 'ci_consulting_business', 'Business Consulting', 'cash_in', 23, NULL, 5),
    (114, 'ci_consulting_it', 'IT Consulting', 'cash_in', 23, NULL, 5),
    (115, 'ci_financial_loan_repayment_received', 'Loan Repayment Received', 'cash_in', 0, NULL, 6),
    (116, 'ci_financial_stock_exchange', 'Stock-Exchange Income', 'cash_in', 0, NULL, 6),
    (117, 'ci_financial_other', 'Other Financial Income', 'cash_in', 0, NULL, 6),
    (118, 'ci_financial_loan_taken', 'Loan Taken', 'cash_in', 0, NULL, 6),
    (119, 'ci_other_rent', 'Rent', 'cash_in', 23, NULL, 7),
    (120, 'ci_other_income', 'Other Income', 'cash_in', 23, NULL, 7),

    (121, 'co_marketing_paid_ads', 'Paid Ads', 'cash_out', 23, 100, 8),
    (122, 'co_marketing_seo', 'SEO', 'cash_out', 23, 100, 8),
    (123, 'co_marketing_agent_fees', 'Agent / Referral Fees', 'cash_out', 23, 100, 8),
    (124, 'co_operations_rent', 'Rent', 'cash_out', 23, 100, 9),
    (125, 'co_operations_utilities', 'Utilities', 'cash_out', 23, 100, 9),
    (126, 'co_operations_office_supplies', 'Office Supplies', 'cash_out', 23, 100, 9),
    (127, 'co_operations_transport', 'Transport / Petrol', 'cash_out', 23, 50, 9),
    (128, 'co_operations_small_equipment', 'Small Equipment', 'cash_out', 23, 100, 9),
    (129, 'co_operations_maintenance', 'Maintenance / Repairs', 'cash_out', 23, 100, 9),
    (130, 'co_people_salaries', 'Salaries', 'cash_out', 0, 0, 10),
    (131, 'co_people_bonuses', 'Bonuses / Additional Payments', 'cash_out', 0, 0, 10),
    (132, 'co_people_employee_zus', 'Employee ZUS', 'cash_out', 0, 0, 10),
    (133, 'co_people_employee_pit', 'Employee PIT', 'cash_out', 0, 0, 10),
    (134, 'co_people_contractors', 'Contractors', 'cash_out', 23, 100, 10),
    (135, 'co_taxes_vat', 'VAT Payments', 'cash_out', 0, 0, 11),
    (136, 'co_taxes_income_tax', 'Income Tax', 'cash_out', 0, 0, 11),
    (137, 'co_taxes_owner_zus', 'Owner ZUS', 'cash_out', 0, 0, 11),
    (138, 'co_services_accountant', 'Accountant', 'cash_out', 23, 100, 12),
    (139, 'co_services_software', 'Software / SaaS', 'cash_out', 23, 100, 12),
    (140, 'co_services_other', 'Other Services', 'cash_out', 23, 100, 12),
    (141, 'co_financial_bank_fees', 'Bank Fees', 'cash_out', 0, 0, 13),
    (142, 'co_financial_loan_repayment', 'Loan Repayment', 'cash_out', 0, 0, 13),
    (143, 'co_financial_stock_exchange', 'Stock-Exchange Cash Out', 'cash_out', 0, 0, 13),
    (144, 'co_financial_other', 'Other Financial Costs', 'cash_out', 0, 0, 13),
    (145, 'co_financial_loan_given', 'Loan Given', 'cash_out', 0, 0, 13),
    (146, 'co_inventory_devices', 'Devices for Resale', 'cash_out', 23, 100, 14),
    (147, 'co_inventory_supplements', 'Supplements', 'cash_out', 23, 100, 14),
    (148, 'co_inventory_accessories', 'Accessories', 'cash_out', 23, 100, 14),
    (149, 'co_capex_machines', 'Machines', 'cash_out', 23, 100, 15),
    (150, 'co_capex_equipment', 'Equipment', 'cash_out', 23, 100, 15),
    (151, 'co_capex_renovation', 'Renovation / Improvements', 'cash_out', 23, 100, 15),
    (152, 'co_training_int_course_fees', 'Course Fees', 'cash_out', 23, 100, 16),
    (153, 'co_training_int_hotel', 'Hotel', 'cash_out', 8, 100, 16),
    (154, 'co_training_int_transport', 'Transport', 'cash_out', 23, 100, 16),
    (155, 'co_training_int_food', 'Food / Catering', 'cash_out', 8, 100, 16),
    (156, 'co_training_int_other', 'Other Training Costs', 'cash_out', 23, 100, 16),
    (157, 'co_training_del_preparation', 'Preparation Costs', 'cash_out', 23, 100, 17),
    (158, 'co_training_del_travel', 'Travel', 'cash_out', 23, 100, 17),
    (159, 'co_training_del_food', 'Food / Catering', 'cash_out', 8, 100, 17),
    (160, 'co_training_del_commissions', 'Commissions', 'cash_out', 23, 100, 17),
    (161, 'co_private_withdrawals', 'Private Withdrawals', 'cash_out', 0, 0, 18),
    (162, 'co_other_expense', 'Other Expense', 'cash_out', 23, 100, 19);
